name: Node.js CI

on:
  release:
    types: [created]

jobs:
  build-offline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install cli angular
        run: sudo npm install -g @angular/cli
      - name: Install dependencies and build
        run: npm ci --legacy-peer-deps && ng build --prod --serviceWorker false
      - name: build_tar
        run: tar -czvf dist.tar.gz dist/*
      - name: upload offline artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist.tar.gz
          asset_name: dist.tar.gz
          asset_content_type: application/gzip
  build-with-pwa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install cli angular
        run: sudo npm install -g @angular/cli
      - name: Install dependencies and build
        run: npm ci --legacy-peer-deps && ng build --prod --serviceWorker true
      - name: build_tar
        run: tar -czvf dist.tar.gz dist/*
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist.tar.gz
          asset_name: dist_pwa.tar.gz
          asset_content_type: application/gzip          
